# Generated by Django 5.2.6 on 2025-10-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passenage',
            new_name='Passenger',
        ),
    ]
